### ISSUE TITLE
Unpublished item can not be deleted

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder-server#205]

**Comment by nicosantangelo** [comment]
This seems to be a problem in production (more specifically the .io environment). The error is:

`The item was published. It can't be deleted` 

But it's being thrown by the server by new items that don't have a collection. This *does not* happen in development. So my assumption is that there's a collection with id `undefined` in the server's database.

The code looks like this:

```ts
const dbItem = await Item.findOne<ItemAttributes>({ id })
const dbCollection = await Collection.findOne<CollectionAttributes>(
  dbItem!.collection_id!
)

if (dbCollection) {
  const remoteCollections = await collectionAPI.fetchCollection(
    dbCollection.contract_address
  )

  if (remoteCollections) {
    throw new HTTPError(
      "The item was published. It can't be deleted",
      {
        id,
        blockchain_item_id: dbItem!.blockchain_item_id,
        contract_address: dbCollection.contract_address,
      },
      STATUS_CODES.unauthorized
    )
  }
}
```

Can we check that? the problem might be figuring out how that happened..if I'm right
@nachomazzara
