### ISSUE TITLE
Add curation list

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder-server#268]
- Add a new table `curation` to set collections as ready for review:

```
id: (primary key)
collectionId: uuid (foreign key)
timestamp: Date
```

- Add a new endpoint `@PUT /curations/:collectionId` to set a collection ready for review.

- Add a new endpoint to fetch curations
 * `@GET /curations`: this should return a distinct by collectionId. If it is a member of the committee return all the curations, if it is not, return the curation of your collections. *ALWAYS WITH A DISTINCT BY COLLECTION ID*
* `@GET /curations/:collectionId`: return the last curation per collection id

**Comment by fzavalia** [comment]
In Progress until full integration with builder ui has been tested
