### ISSUE TITLE
Lock a TPW collection

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder-server#299]
Related: https://github.com/decentraland/builder-server/issues/278

Use the lock created in #278 to:
- A Third Party collection is locked if the lock is lower than 1 day and the number of items in the database is different from the items in the collection in the subgraph (blockchain)
```ts
if (collection.lock + 1 day > Date.now() && collection.itemsCount() != remoteCollection.itemsCount()) {
     return true // collection is lock
}
```
- We should reject changes in the collection and items if the collection is locked
- Add tests

**Comment by LautaroPetaccio** [comment]
The TP collections won't be locked.
