### ISSUE TITLE
Pool endpoint

### ISSUE THREAD

**Issue by cazala** [decentraland/builder-server#31]
We need and endpoint to add a users scene to the LAND pool. This endpoint should store a snapshot of the project data, the manifest, and the media associated with that project.

A possible implementation could be:

```
POST /pool
Authorization: Bearer {token}
{ "id": "77baa481-611e-460d-9642-1bb4d7ed659e" }
```

That upserts a row in a `Pool` table that has the same schema as the `Project` table, copies the project manifest in s3 to a `pool` directory, along with the media for that project (thumbnail and screenshots). This endpoint should be protected and return a 401 if the user is unauthenticated or unauthorized.

```
GET /pool
{ "ok" true, "data": [ array of projects ] }
```

Returns all the projects in the pool. Once we do pagination and filters for the `/projects` endpoint we should apply those too to this one.

**Comment by nicosantangelo** [comment]
Remember add `/pools/:id/manifest`
