### ISSUE TITLE
Upsert Assetpack (endpoint)

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder-server#40]
PUT `/assetPacks/:id`
Should validate auth
Creates or updates an asset pack

Where AssetPack:

```
{
  id: string
  title: string
  thumbnail: string
  url: string
  assets: Asset[]
}
```
And Asset:

```
{
  assetPackId: string
  id: string
  name: string
  url: string
  thumbnail: string
  tags: string[]
  category: string 
  contents: Record<string, string>
}
```

And the actual contents would be sent as multipart where key is the file's CID and value is a Blob (to be matched agains the contents' record)

**Comment by nicosantangelo** [comment]
We'll probably need to add something like

`POST /assets/:id/media` for each file Blob
