### ISSUE TITLE
Filter curations by status

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder-server#416]
We need to add a new Query String to curation endpoints that allows the caller to filter the result by CurationStatus.

It could look like this:
`?status=pending`

To complete the task:
- [ ] Check if it's necessary to add on both item and collection curations. To start, item curations should be enough but it'll be useful in both
- [ ] Filter the curations by the supplied status only if present. Keep in mind items curations are only getting the last ItemCuration for a collection
- [ ] Validate the status is valid

**Comment by LautaroPetaccio** [comment]
Closing issue due to being irrelevant at the moment.
