### ISSUE TITLE
The collections retrieved for the collections page are not ordered by creation date

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/builder-server#535]
## 🎉 Description

The curations displayed in the collections page (where creators see all of their collections) are not listed by creation date, making new collections move to other pages, possibly confusing creators.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## Steps to reproduce

1. Create a new third party collection.
2. Add items to the collection (optional).
3. Go to the collections page and check that the collection is not the first element in the collections page.

**Comment by juanmahidalgo** [comment]
Fix in #536
