### ISSUE TITLE
Modifying a third party item results in the item being last in the item's pages of the collection

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/builder-server#538]
## 🎉 Description

After modifying an item and querying the items of a collection again, the item is placed last in the list of items. The list of items of a collection should be shown in the order that they were created instead of the order on which they were modified. Changing the order of the items might be confusing for the user.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
Will be fixed in https://github.com/decentraland/builder-server/pull/541
